version: '3.8'

services:
  weather-app:
    build: .
    command: tail -f /dev/null
    depends_on:
      - documentation

  documentation:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./docs:/usr/share/nginx/html